### 일기 작성
POST http://localhost:8080/create/diary
Content-Type: application/json

{
  "writeAt": "2024-08-29",
  "cityName": "seoul",
  "contents": "일기 내용 테스트"
}

### 일기 조회
GET http://localhost:8080/read/diary
Content-Type: application/json

{
  "writeDate": "2024-08-29"
}