### 일기 작성
POST http://localhost:8080/create/diary
Content-Type: application/json

{
  "writeAt": "2024-08-31",
  "cityName": "seoul",
  "contents": "일기 내용 테스트"
}

### 특정 날짜에 작성된 일기 조회
GET http://localhost:8080/read/diary
Content-Type: application/json

{
  "writeDate": "2024-08-31"
}

### 특정 기간동안 작성된 일기 조회
GET http://localhost:8080/read/diaries
Content-Type: application/json

{
  "startDate": "2024-08-28",
  "endDate": "2024-08-31"
}

### 일기 수정
PUT http://localhost:8080/update/diary
Content-Type: application/json

{
  "writeAt": "2024-08-31",
  "contents": "일기 내용 수정 테스트"
}

### 특정 날짜에 작성된 모든 일기 삭제
DELETE http://localhost:8080/delete/diary
Content-Type: application/json

{
  "writeAt": "2024-08-31"
}